# Generated by Django 4.2.4 on 2023-08-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="Отчество",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        help_text="+375(29)123-45-67",
                        max_length=17,
                        unique=True,
                        verbose_name="Моб. тел.",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="user@gmail.com",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Почта",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Загружено в базу"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлено в базе"
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
    ]
